-- 1. BANKS TABLE
CREATE TABLE BANKS (
    BANK_ID NUMBER(5) PRIMARY KEY,
    BANK_NAME VARCHAR2(100) NOT NULL UNIQUE,
    BANK_CODE VARCHAR2(10) UNIQUE NOT NULL,
    HEADQUARTERS VARCHAR2(100),
    SUPPORT_PHONE VARCHAR2(15)
);

-- 2. FARMERS TABLE
CREATE TABLE FARMERS (
    FARMER_ID NUMBER(10) PRIMARY KEY,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    ID_NUMBER VARCHAR2(20) UNIQUE NOT NULL,
    PHONE VARCHAR2(15) NOT NULL CHECK (PHONE LIKE '+250%'),
    FARM_SIZE_ACRES NUMBER(8,2) CHECK (FARM_SIZE_ACRES > 0),
    LOCATION VARCHAR2(100) NOT NULL,
    BANK_ACCOUNT_NUMBER VARCHAR2(30),
    BANK_ID NUMBER(5) REFERENCES BANKS(BANK_ID),
    REGISTRATION_DATE DATE DEFAULT SYSDATE NOT NULL
);

-- 3. LANDS TABLE
CREATE TABLE LANDS (
    LAND_ID NUMBER(10) PRIMARY KEY,
    FARMER_ID NUMBER(10) NOT NULL REFERENCES FARMERS(FARMER_ID),
    LAND_REGISTRATION_NUMBER VARCHAR2(50) UNIQUE NOT NULL,
    LAND_SIZE_ACRES NUMBER(8,2) NOT NULL CHECK (LAND_SIZE_ACRES > 0),
    LOCATION VARCHAR2(100) NOT NULL,
    DISTRICT VARCHAR2(50),
    SECTOR VARCHAR2(50),
    CELL VARCHAR2(50),
    VILLAGE VARCHAR2(50),
    OWNERSHIP_TYPE VARCHAR2(20) DEFAULT 'OWNED'
        CHECK (OWNERSHIP_TYPE IN ('OWNED', 'LEASED', 'COMMUNAL', 'GOVERNMENT')),
    REGISTRATION_DATE DATE DEFAULT SYSDATE,
    LAND_CERTIFICATE_PATH VARCHAR2(500)
);

-- 4. SUPPLIERS TABLE
CREATE TABLE SUPPLIERS (
    SUPPLIER_ID NUMBER(10) PRIMARY KEY,
    SUPPLIER_NAME VARCHAR2(100) NOT NULL,
    SUPPLIER_TYPE VARCHAR2(30) DEFAULT 'GOVERNMENT'
        CHECK (SUPPLIER_TYPE IN ('GOVERNMENT', 'NGO', 'PRIVATE', 'BANK')),
    SUPPLIER_BANK_ID NUMBER(5) REFERENCES BANKS(BANK_ID),
    BANK_ACCOUNT_NUMBER VARCHAR2(30),
    EMAIL VARCHAR2(100),
    PHONE VARCHAR2(15),
    ADDRESS VARCHAR2(200),
    REGISTRATION_DATE DATE DEFAULT SYSDATE NOT NULL
);

-- 5. SUBSIDY_TYPES TABLE
CREATE TABLE SUBSIDY_TYPES (
    TYPE_ID NUMBER(5) PRIMARY KEY,
    TYPE_NAME VARCHAR2(50) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR2(200),
    MAX_AMOUNT NUMBER(12,2) CHECK (MAX_AMOUNT > 0),
    UNIT VARCHAR2(20),
    SUPPLIER_ID NUMBER(10) NOT NULL REFERENCES SUPPLIERS(SUPPLIER_ID)
);

-- 6. APPLICATIONS TABLE
CREATE TABLE APPLICATIONS (
    APPLICATION_ID NUMBER(10) PRIMARY KEY,
    FARMER_ID NUMBER(10) NOT NULL REFERENCES FARMERS(FARMER_ID),
    LAND_ID NUMBER(10) NOT NULL REFERENCES LANDS(LAND_ID),
    SUBSIDY_TYPE_ID NUMBER(5) NOT NULL REFERENCES SUBSIDY_TYPES(TYPE_ID),
    APPLICATION_DATE DATE DEFAULT SYSDATE NOT NULL,
    AMOUNT_REQUESTED NUMBER(12,2) NOT NULL CHECK (AMOUNT_REQUESTED > 0),
    PREFERRED_BANK_ID NUMBER(5) REFERENCES BANKS(BANK_ID),
    STATUS VARCHAR2(20) DEFAULT 'PENDING' 
        CHECK (STATUS IN ('PENDING', 'APPROVED', 'REJECTED', 'PAID'))
);

-- 7. PAYMENTS TABLE
CREATE TABLE PAYMENTS (
    PAYMENT_ID NUMBER(10) PRIMARY KEY,
    APPLICATION_ID NUMBER(10) NOT NULL REFERENCES APPLICATIONS(APPLICATION_ID),
    SUPPLIER_ID NUMBER(10) NOT NULL REFERENCES SUPPLIERS(SUPPLIER_ID),
    FROM_BANK_ID NUMBER(5) NOT NULL REFERENCES BANKS(BANK_ID),
    TO_BANK_ID NUMBER(5) NOT NULL REFERENCES BANKS(BANK_ID),
    PAYMENT_DATE DATE DEFAULT SYSDATE NOT NULL,
    AMOUNT NUMBER(12,2) NOT NULL CHECK (AMOUNT > 0),
    BANK_REFERENCE VARCHAR2(50) UNIQUE NOT NULL,
    PAYMENT_STATUS VARCHAR2(20) DEFAULT 'PENDING'
        CHECK (PAYMENT_STATUS IN ('PENDING', 'COMPLETED', 'FAILED', 'REVERSED'))
);

--8. CUSTOMER_MESSAGES TABLE
CREATE TABLE CUSTOMER_MESSAGES (
    MESSAGE_ID NUMBER PRIMARY KEY,
    FARMER_ID NUMBER REFERENCES FARMERS(FARMER_ID),
    MESSAGE_TYPE VARCHAR2(20) CHECK (MESSAGE_TYPE IN ('ERROR', 'SUCCESS', 'NOTIFICATION')),
    MESSAGE_TEXT VARCHAR2(1000),
    PHONE_NUMBER VARCHAR2(15),
    STATUS VARCHAR2(20) DEFAULT 'PENDING' CHECK (STATUS IN ('PENDING', 'SENT', 'FAILED')),
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    SENT_DATE TIMESTAMP
);

CREATE TABLE REPEAT_ERROR_ALERTS (
    ALERT_ID NUMBER PRIMARY KEY,
    USER_NAME VARCHAR2(100),
    ERROR_TYPE VARCHAR2(100),
    ERROR_COUNT NUMBER,
    FIRST_OCCURRENCE DATE,
    LAST_OCCURRENCE DATE,
    ALERT_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(20) DEFAULT 'PENDING',
    ACTION_TAKEN VARCHAR2(200)
);


CREATE TABLE PUBLIC_HOLIDAYS (
    HOLIDAY_ID NUMBER PRIMARY KEY,
    HOLIDAY_NAME VARCHAR2(100) NOT NULL,
    HOLIDAY_DATE DATE NOT NULL,
    DESCRIPTION VARCHAR2(500),
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_BY VARCHAR2(50)
);
--SEQUENCES
-- 1. Sequence for BANKS table
CREATE SEQUENCE BANK_SEQ 
START WITH 1001          
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 2. Sequence for SUPPLIERS table  
CREATE SEQUENCE SUPPLIER_SEQ
START WITH 2001          
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 3. Sequence for FARMERS table
CREATE SEQUENCE FARMER_SEQ
START WITH 3001          
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 4. Sequence for LANDS table
CREATE SEQUENCE LAND_SEQ
START WITH 4001          
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 5. Sequence for SUBSIDY_TYPES table
CREATE SEQUENCE SUBSIDY_TYPE_SEQ
START WITH 5001          
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 6. Sequence for APPLICATIONS table
CREATE SEQUENCE APPLICATION_SEQ
START WITH 6001          
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 7. Sequence for PAYMENTS table
CREATE SEQUENCE PAYMENT_SEQ
START WITH 7001          
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE MESSAGE_SEQ START WITH 1;

CREATE SEQUENCE ALERT_SEQ START WITH 100 INCREMENT BY 1;

CREATE SEQUENCE HOLIDAY_SEQ START WITH 1 INCREMENT BY 1;
