SELECT
    S.SUPPLIER_NAME,
    ST.TYPE_NAME,
    COUNT(P.PAYMENT_ID) AS TOTAL_PAYMENTS,
    SUM(P.AMOUNT) AS TOTAL_AMOUNT
FROM PAYMENTS P
    JOIN SUPPLIERS S ON P.SUPPLIER_ID = S.SUPPLIER_ID
    JOIN APPLICATIONS A ON P.APPLICATION_ID = A.APPLICATION_ID
    JOIN SUBSIDY_TYPES ST ON A.SUBSIDY_TYPE_ID = ST.TYPE_ID
GROUP BY S.SUPPLIER_NAME, ST.TYPE_NAME;

---

SELECT
    F.FIRST_NAME ||''||F.LAST_NAME AS FARMER,
    S.SUPPLIER_NAME AS FUND_SOURCE,
    B_FROM.BANK_NAME AS FROM_BANK,
    B_TO.BANK_NAME AS TO_BANK,
    P.AMOUNT,
    P.PAYMENT_DATE,
    P.BANK_REFERENCE
FROM PAYMENTS P
JOIN APPLICATIONS A ON P.APPLICATION_ID = A.APPLICATION_ID
JOIN FARMERS F ON A.FARMER_ID = F.FARMER_ID
JOIN SUPPLIERS S ON P.SUPPLIER_ID = S.SUPPLIER_ID
JOIN BANKS B_FROM ON P.FROM_BANK_ID = B_FROM.BANK_ID
JOIN BANKS B_TO ON P.TO_BANK_ID = B_TO.BANK_ID
WHERE P.PAYMENT_STATUS ='COMPLETED';
